notifications:
  email: false

dist: trusty

sudo: false


matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

language: node_js
node_js:
  - "8.10.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - gnome-keyring
      - libsecret-1-dev
      - python-gnomekeyring
script:
  - ./script/test && ./script/package
