notifications:
  email: false

dist: trusty

sudo: false


matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

language: node_js
node_js:
  - "8.10.0"

addons:
  apt:
    packages:
      - libsecret-1-dev

script:
  - ./script/test && ./script/package
